### ISSUE TITLE
Expand target scope

### ISSUE THREAD

**Issue by fulldecent** [0xcert/ethereum-erc721#159]
Currently (in v2 branch) we say:

> This is the complete reference implementation of the ERC-721 non-fungible token standard for the Ethereum blockchain.

This is unnecessarily limiting. This repository is also compatible with Hyperledger, https://poa.network, Ethereum Classic, and other networks.

Maybe there is an elegant way we can say this without adding the responsibility of testing against all those networks.

---

# Work plan 

- [ ] Identify live public EVM-compatible networks and private networks
- [ ] Test this package against all of them
- [ ] Create scripts to automatically test against them, using the toolchain that is customary for those projects
- [ ] Add those scripts to this project's CI
- [ ] Expand the project scope

**Comment by xpepermint** [comment]
We haven't tested these contracts on other systems. I'd say we test them elsewhere then we get back to this issue and write a precise message.

**Comment by fulldecent** [comment]
Sounds good. I can handle this after 2.0.0 final.

**Comment by MoMannn** [comment]
This has been tested and tried on avalanche and binance smart chain. There is no reason to believe it would not work on any EVM compatible chains depending that are running `Constantinople` or newer forks.

https://github.com/0xcert/ethereum-erc721/pull/266
